//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo_Matricula
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grado
    {
        public int IdGrado { get; set; }
        public Nullable<int> IdAlumno { get; set; }
        public string Grupo { get; set; }
        public string CodigoNacionalDeEstudiante { get; set; }
        public string EstadoDelEstudiante { get; set; }
        public string CentroDeProcedencia { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
    }
}
