//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo_Matricula
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grado
    {
        public int IdGrado { get; set; }
        public Nullable<int> IdAlumno { get; set; }
        public string Grupo { get; set; }
        public string CodigoNacionalDeEstudiante { get; set; }
        public string EstadoDelEstudiante { get; set; }
        public string CentroDeProcedencia { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
    }
}
