//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo_Matricula
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int IdMatricula { get; set; }
        public Nullable<int> IdAlumno { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
