//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo_Matricula
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsableLegal
    {
        public int IdResponsable { get; set; }
        public Nullable<int> IdAlumno { get; set; }
        public string Nombre { get; set; }
        public string Parentesco { get; set; }
        public string NumeroDeCedula { get; set; }
        public string Ocupacion { get; set; }
        public string LugarDeTrabajo { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public string DireccionDelResponsable { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
    }
}
